Sprint 3/step 1
ShmidtOtto/react-burger pull request #4
Opened 2023-12-26 14:12 UTC by ShmidtOtto

2023-12-26 16:10 UTC, ArslanMustafin requested changes
## Code Review

Здравствуйте!

Отличная работа.

### **Вы молодец!**

- Сборка и запуск проекта выполняются без ошибок;
- Теперь у вас есть роутинг;
- Есть регистрация и авторизация;

### **Но есть несколько замечаний, которые нужно исправить:**

- <https://disk.yandex.com/i/RGGLoRu5ufkm7A> - Активной должна быть только одна ссылка, та, на которой сейчас находиться пользователь;

- В директории `components` должен быть компонент App. Компонент `App`, он также должен быть в папке (как и другие компоненты). Как правило, это основной компонент в React, который выступает в качестве контейнера для всех остальных компонентов;

- Вы должны добавлять в хедер запроса `POST /orders`, токен пользователя `Bearer ...`, чтобы сервер понимал что заказ сделал зарегистрированный пользователь (время обработки заказа должно быть в разы больше, если вы всё правильно сделали);

- В запросе `POST /orders` нужно передавать id булок, а не весь объект, а также нужно чтобы id у булок были в начале и в конце массива: <https://disk.yandex.com/i/uMAbTH2O2-HNQA>;

- При клике по ингредиенту возникает модальное окно, но если перезагрузить страницу, то ингредиент не отображается <https://disk.yandex.com/i/9_mQBtfupf_Zxw>. Прошу обратить внимание на запрос `GET - /ingredients` (получение ингредиентов), его лучше делать всего 1 раз, в компоненте `app`;

- Не хватает пустого поля с паролем, пользователь должен иметь возможность задать новый пароль. <https://disk.yandex.com/i/u_d8A43S9Rfm5g>

- По чек-листу, требуется реализовать:

  - `/reset-password` доступен неавторизованным пользователям только после посещения маршрута `/forgot-password` и ввода адреса электронной почты для восстановления пароля;

  - При попытке неавторизованных пользователей перейти на защищённые роуты происходит редирект на `/login`. После успешной авторизации происходит переадресация на тот маршрут, к которому пользователь не получил доступ ранее.

### **Сделает код лучше:**

- Стоит обращать внимание на предупреждения в терминале, в котором запущен проект. Это хорошие рекомендации, которых следовало бы придерживаться. В противном случае, лучше отключить линтер у строки (куска кода) eslint-disable. Так же добавить комментарий (TODO), объясняющий причину блокировки линтера в данном месте. Суть в том, что мы стараемся писать более чистый код, а если видим, что порой выскакивают предупреждения того же линтера, то оставляем комментарий, объясняющий причину. В коммерческой разработке, когда есть целая команда разработчиков, работающих над одним проектом, эта рекомендация послужит правилом хорошего тона. Неплохая статься по поводу локального отключения линтера: <https://learn.coderslang.com/ru/0023-eslint-disable-for-specific-lines-files-and-folders>

#### **Хочу напомнить, что работа может быть принята, только после исправления всех "Надо исправить". Перед отправкой на ревью, проверьте работоспособность проекта и наличие возможных ошибок в консоли браузера (кнопка F12).**

2023-12-26 16:10 UTC, ArslanMustafin commented on src/components/app-header/app-header.jsx
> +                            let icon = isActive ? <BurgerIcon type="primary" /> : <BurgerIcon type="secondary" />;
**Надо исправить:**

Здесь и далее.

1. Нужно использовать `const`, а не `let`, в коде ведь нет переопределения переменной)
2. Лучше написать так: `const icon = <BurgerIcon type={isActive ? "primary" :  "secondary"} />`

2023-12-26 16:10 UTC, ArslanMustafin commented on src/pages/forgot-password/forgot-password.jsx
> +            debugger;
**Можно лучше:**

Старайтесь убирать логи и дебаггеры, перед сдачей работы)

2023-12-26 16:10 UTC, ArslanMustafin commented on src/pages/home/home.jsx
> +    }, [ingredientsUrl, dispatch]);
**Надо исправить:**

лучше переместить вызов в компонент `app` и не нужно указывать зависимости)) там они не нужны.

2023-12-26 16:10 UTC, ArslanMustafin commented on src/pages/home/home.jsx
> +    }
**Можно лучше:**

лучше сделать вернуть текст ошибки), чтобы `jsx` не рендерился с ошибкой.

2023-12-26 16:10 UTC, ArslanMustafin commented on src/pages/ingredient/ingredient.jsx
> +    }, [ingredientsUrl, ingredients, id, dispatch]);
**Надо исправить:**

Нужно убрать запрос на получение ингредиентов, как я и говорил ранее, лучше его переместить в `app`  и он будет вызываться всего 1 раз.

В зависимостях можно оставить только `id` и `ingredients`

2023-12-26 16:10 UTC, ArslanMustafin commented on src/pages/login/login.jsx
> +            }
**Надо исправить:**

здесь не нужно делать никаких проверок, этот функционал уже есть в `protect-route`.
Тут просто `dispatch(login(loginFormData))`

2023-12-26 16:10 UTC, ArslanMustafin commented on src/utils/api/user-api/index.js
> +const register = async (email, password, name) => {
**Надо исправить:**

здесь и далее.

тут нужно использовать обычный `fetch`, а не `fetchWithRefresh`

2023-12-26 16:10 UTC, ArslanMustafin commented on src/components/protected-route/index.jsx
> +    return <Navigate to='/login' />;
**Надо исправить:**

Тут нужно добавить пропс `state={{ from: location }}`. Для того чтобы правильно работал редирект выше (14 строчка).

2023-12-26 16:10 UTC, ArslanMustafin commented on src/App.jsx
> +  const from = location.state && location.state.from;
**Надо исправить:**

нужно поменять поле `from` на `background` (это пример, можно любое название, но `from` лучше не использовать, т.к. туда вы уже кладёте прошлую страницу). Не забудьте поменять стейт в https://github.com/ShmidtOtto/react-burger/blob/sprint-3/step-1/src/components/burger-ingredients/burger-ingredients-cart/burger-ingredients-cart.jsx#L42

2023-12-26 16:10 UTC, ArslanMustafin commented on src/App.jsx
> +          <Route path='/profile' element={<ProfileLayout />}>
**Надо исправить:**

Думаю, тут тоже нужно использовать `OnlyAuth`

2023-12-27 06:20 UTC, ShmidtOtto commented
Немного не понял на счёт компонента App, напишите пожалуйста подробнее

2023-12-27 12:53 UTC, ArslanMustafin approved these changes
## Code Review

Здравствуйте!

Отличная работа.

### **Вы молодец! Работа принята, удачи в дальнейшем обучении!**

- Все замечания были исправлены;

### **Сделает код лучше:**

- По поводу компонента `App` просто перенесите его в `components` и создайте для него папку `app`;

2023-12-27 12:53 UTC, ArslanMustafin commented on src/App.jsx
> +  }, []);
**Можно лучше:**

Это можно перенести в `useEffect` ниже, тогда у вас будет только один `useEffect`

2023-12-27 12:53 UTC, ArslanMustafin commented on src/components/app-header/app-header-tab/app-header-tab.jsx
> +            <p className={cn('text', 'ml-2', 'text_type_main-default', active ? '' : 'text_color_inactive')}>{text}</p>
**Можно лучше:**

```suggestion
      <p className={cn('text', 'ml-2', 'text_type_main-default', { text_color_inactive: !active })}>
        {text}
      </p>
```

2023-12-27 12:53 UTC, ArslanMustafin commented on src/components/modals/order-details/order-details.jsx
>      }, [duspach, constructorIngredients, buns]);
**Рекомендую исправить:**

Это должен делать обработчик события в `burger-constructor`. Т.к. модальное окно `order-details` должно просто отвечать за отображение

2023-12-29 07:05 UTC, merged