Sprint 6/step 1
ShmidtOtto/react-burger pull request #7
Opened 2024-02-20 10:38 UTC by ShmidtOtto

2024-02-20 10:47 UTC, ShmidtOtto commented
Для сборки проекта используйте пожалуйста ```npm --force install```

2024-02-20 11:42 UTC, ArslanMustafin requested changes
## Code Review

Здравствуйте!

Отличная работа. 🔥

### **Вы молодец!**

- Все юнит-тесты проходят успешно.
- Все Cypress тесты проходят успешно.
- В readme есть ссылка на проект.

### **Есть небольшое замечание, которое нужно исправить:**

- Нужно добавить cypress-тесты для проверки модального окна, а именно:

  - открытие модального окна с описанием ингредиента,
  - отображение в модальном окне данных ингредиента,
  - закрытие модальных окон при клике на кнопку закрытия.

### **Сделает код лучше:**

- Добавьте команду в `package.json` для открытия cypres: `"cypress:open": "./node_modules/.bin/cypress open"`, так намного удобнее запускать cypress.;

- Стоит обращать внимание на предупреждения в терминале, в котором запущен проект. Это хорошие рекомендации, которых следовало бы придерживаться. В противном случае, лучше отключить линтер у строки (куска кода) eslint-disable. Так же добавить комментарий (TODO), объясняющий причину блокировки линтера в данном месте. Суть в том, что мы стараемся писать более чистый код, а если видим, что порой выскакивают предупреждения того же линтера, то оставляем комментарий, объясняющий причину. В коммерческой разработке, когда есть целая команда разработчиков, работающих над одним проектом, эта рекомендация послужит правилом хорошего тона. Неплохая статься по поводу локального отключения линтера: <https://learn.coderslang.com/ru/0023-eslint-disable-for-specific-lines-files-and-folders>;

2024-02-20 11:42 UTC, ArslanMustafin commented on cypress/e2e/buy-burger.cy.ts
> +    cy.getBySel('643d69a5c3f7b9001cfa0947').drag('[data-test-id=constructor]');
**Можно лучше:**

Лучше вынести id ингредиентов в отдельные переменные

2024-02-20 11:42 UTC, ArslanMustafin commented on src/services/reducers/constructorIngredientsReducer.test.js
> +        };
**Можно лучше:**

лучше чуть выше вынести ингредиент или несколько ингредиентов, и переиспользовать их в других тестах.

2024-02-20 12:54 UTC, ShmidtOtto commented
Исправил замечания

2024-02-21 04:35 UTC, ArslanMustafin approved these changes
## Code Review

Здравствуйте!

Отличная работа.🔥

### **Вы молодец! Работа принята.**

Несколько советов для дальнейшего развития:

- Сверстайте несколько небольших проектов для себя, для закрепления знаний, и чтобы можно добавить их в портфолио.

- Ходите на собеседования: опыт прохождения собеседований не менее важен знаний теории, и Вы поймете, какие знания требуются на рынке, и где Вы проседаете.

- Читайте habr и слушаете подкасты: они очень хорошо расширяют кругозор и позволяют узнать, что происходит в отрасли.

2024-02-21 04:49 UTC, merged